- name: Download Tomcat9 from tomcat.apache.org
  hosts: tomcat
  become: yes

  tasks:
   - name: Download Open JDK
     apt:
      name: openjdk-17-jdk
      update_cache: yes
      state: present
   - name:  install net-tools
     apt:
      name: net-tools
      update_cache: yes
      state: present
   - name: Create the group
     group: 
      name: www-data
      state: present
   - name: Create the user
     user:
        name: www-data
        state: present
   - name: Download Tomcat
     get_url:  
       url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.76/bin/apache-tomcat-9.0.76.tar.gz
       dest: /tmp/apache-tomcat-9.0.76.tar.gz

   - name: Extract archive
     unarchive:  
      src: /tmp/apache-tomcat-9.0.76.tar.gz 
      dest: /opt/
      mode: 0755
      remote_src: yes
      group: www-data
      owner: www-data
   - name: Copy the user role tomcat-users.xml
     copy:
        src: tomcat-users.xml
        dest: /opt/apache-tomcat-9.0.76/conf/tomcat-users.xml
   - name: Creating a service file
     copy: 
      content: |-
        [Unit]
        Description=Tomcat Service
        Requires=network.target
        After=network.target
        [Service]
        Type=forking
        User=www-data
        Grooup=www-data
        Environment="CATALINA_PID=/opt/apache-tomcat-9.0.76/logs/tomcat.pid"
        Environment="CATALINA_BASE=/opt/apache-tomcat-9.0.76"
        Environment="CATALINA_HOME=/opt/apache-tomcat-9.0.76"
        Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
        ExecStart=/opt/apache-tomcat-9.0.76/bin/startup.sh
        ExecStop=/opt/apache-tomcat-9.0.76/bin/shutdown.sh
        Restart=on-abnormal
        [Install]
        WantedBy=multi-user.target
      dest: /etc/systemd/system/tomcat.service
     notify:
       - Reload SystemD
       - Restart tomcat        
   - name: copy manager context.xml
     copy:
        src: context.xml
        dest: /opt/apache-tomcat-9.0.76/webapps/manager/META-INF
     notify:
       - Reload SystemD
       - Restart tomcat
   - name: copy host manager context.xml
     copy:
        src: hostmanager-context.xml
        dest: /opt/apache-tomcat-9.0.76/webapps/host-manager/META-INF/context.xml
     notify: 
       - Reload SystemD
       - Restart tomcat
   - name: restart tomcat
     systemd:
        name: tomcat
        enabled: yes
        state: started
